name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite UTC
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: V1ni0menega
          outputs: dist/github-contribution-grid-snake.svg

      - name: Enviar para o repositório
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
